--
--  ROLLBACK ON MALNUTRITIONCONTROL CHANGES (step_23_wardpharmacy20.sql)
--

INSERT INTO PATIENTEXAMINATION (PEX_DATE, PEX_PAT_ID, PEX_HEIGHT, PEX_WEIGHT) 
SELECT MLN_DATE_SUPP, MLN_PAT_ID, IF(MLN_HEIGHT<3, MLN_HEIGHT * 100, MLN_HEIGHT), MLN_WEIGHT FROM MALNUTRITIONCONTROL WHERE MLN_PAT_ID <> 0;

DELETE FROM MALNUTRITIONCONTROL WHERE MLN_ADM_ID = 0;

ALTER TABLE MALNUTRITIONCONTROL DROP COLUMN MLN_PAT_ID, CHANGE COLUMN MLN_ADM_ID MLN_ADM_ID INT(11) NOT NULL;