CREATE TABLE PATIENTEXAMINATION (
	PEX_ID int NOT NULL AUTO_INCREMENT ,
	PEX_DATE datetime NOT NULL ,
	PEX_PAT_ID int NOT NULL ,
	PEX_HEIGHT int NULL ,
	PEX_WEIGHT int NULL ,
	PEX_PA_MIN int NULL ,
	PEX_PA_MAX int NULL ,
	PEX_FC int NULL ,
	PEX_NOTE varchar(300) NULL ,
	
	INDEX ( PEX_PAT_ID  ) ,
	PRIMARY KEY ( PEX_ID )
) ENGINE=MyISAM;

--
-- CONSTRAINTS
--
ALTER TABLE PATIENTEXAMINATION
	ADD CONSTRAINT FK_PATIENTEXAMINATION_PATIENT 
	FOREIGN KEY (PEX_PAT_ID) 
	REFERENCES PATIENT (PAT_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE;
	
