CREATE TABLE PATIENTEXEMPTIONCODE (  
	PAE_PAT_ID INT(11) NOT NULL ,  
	PAE_CODES VARCHAR(100) NOT NULL ,  
	PRIMARY KEY (PAE_PAT_ID)
) Engine=MyISAM;

--
-- CONSTRAINTS
--
ALTER TABLE PATIENTEXEMPTIONCODE
	ADD CONSTRAINT FK_PATIENTEXEMPTIONCODE_PATIENT    
	FOREIGN KEY (PAE_PAT_ID )    
	REFERENCES PATIENT (PAT_ID )
	ON DELETE CASCADE
	ON UPDATE CASCADE;